CREATE DATABASE IF NOT EXISTS BD_ESTOQUE_MERCADO;
USE BD_ESTOQUE_MERCADO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    VALOR DOUBLE NOT NULL,
    FK_CATEGORIA_ID INT,
    FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);

CREATE TABLE IF NOT EXISTS PRODUTO_FORNECEDOR(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_PRODUTO_ID INT,
    FK_FORNECEDOR_CPF VARCHAR(11),
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(ID),
    FOREIGN KEY (FK_FORNECEDOR_CPF) REFERENCES FORNECEDOR(CPF)
);	